### ISSUE TITLE
How to handle `couldn't get a connection after 30.00 sec`

### ISSUE THREAD

**Issue by gameveloster** [procrastinate-org/procrastinate#1116]
When I run a worker and there is a temp issue connecting to the postgres DB (e.g. lost internet connection), the worker will crash with the error 

```
procrastinate.exceptions.RunTaskError: One of the specified coroutines ended with an exception
couldn't get a connection after 30.00 sec
Database error.
One of the specified coroutines ended with an exception
```

Is there a way let the worker continuously retry forever until it reestablishes the DB connection?

**My worker code**

```py
import procrastinate

app = procrastinate.App(
    connector=procrastinate.PsycopgConnector(
        conninfo=get_postgres_connection_string(), kwargs={"prepare_threshold": None}
    )
)

@app.task(queue="test_queue", pass_context=True)
def test_task(context: procrastinate.JobContext, text: str):
  pass
```

**Full trace:**

```log
DEBUG:procrastinate.worker:Waiting for new jobs on queues test_queue
ERROR:procrastinate.utils:Main coroutine error, initiating remaining coroutines stop. Cause: ConnectorException('\n    Database error.\n    ')
INFO:procrastinate.worker:Stop requested
DEBUG:procrastinate.utils:Stopped listener
ERROR:procrastinate.utils:single_worker error: ConnectorException('\n    Database error.\n    ')
NoneType: None
DEBUG:procrastinate.signals:Resetting previous signal handler
DEBUG:procrastinate.cli:Exception details:
Traceback (most recent call last):
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/sync_psycopg_connector.py", line 28, in wrap_exceptions
    yield
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/psycopg_connector.py", line 43, in wrap_exceptions
    yield
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/contextlib.py", line 95, in inner
    return await func(*args, **kwds)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/psycopg_connector.py", line 209, in execute_query_one_async
    async with self._get_cursor() as cursor:
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/psycopg_connector.py", line 187, in _get_cursor
    async with self.pool.connection() as connection:
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/psycopg_pool/pool_async.py", line 191, in connection
    conn = await self.getconn(timeout=timeout)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/psycopg_pool/pool_async.py", line 226, in getconn
    raise PoolTimeout(
psycopg_pool.PoolTimeout: couldn't get a connection after 30.00 sec

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/utils.py", line 292, in run_tasks
    await asyncio.gather(_main(), *side_tasks)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/utils.py", line 284, in _main
    await asyncio.gather(*main_tasks)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/worker.py", line 161, in single_worker
    job = await self.job_manager.fetch_job(self.queues)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/manager.py", line 137, in fetch_job
    row = await self.connector.execute_query_one_async(
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/contextlib.py", line 94, in inner
    async with self._recreate_cm():
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/psycopg_connector.py", line 42, in wrap_exceptions
    with sync_psycopg_connector.wrap_exceptions():
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/sync_psycopg_connector.py", line 32, in wrap_exceptions
    raise exceptions.ConnectorException from exc
procrastinate.exceptions.ConnectorException: 
    Database error.
    

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/cli.py", line 520, in execute_command
    await parsed.pop("func")(app=app, **parsed)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/cli.py", line 542, in worker_
    await app.run_worker_async(**kwargs)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/app.py", line 273, in run_worker_async
    await asyncio.shield(task)
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/worker.py", line 143, in run
    await utils.run_tasks(
  File "/Users/gameveloster/anaconda3/envs/backend/lib/python3.10/site-packages/procrastinate/utils.py", line 363, in run_tasks
    raise exceptions.RunTaskError from exception_records[0].exc
procrastinate.exceptions.RunTaskError: One of the specified coroutines ended with an exception
couldn't get a connection after 30.00 sec
Database error.
One of the specified coroutines ended with an exception
```

**Comment by onlyann** [comment]
This is an area that has room for improvement.

Something you can try is to use a custom connector that inherits from`PsycopgConnector` and adds a retry strategy against the [execute_query_async](https://github.com/procrastinate-org/procrastinate/blob/234f5f0ef3571cd9ff9053ca174c98e18d0f6631/procrastinate/psycopg_connector.py#L201C15-L201C34) , [execute_query_once_async](https://github.com/procrastinate-org/procrastinate/blob/234f5f0ef3571cd9ff9053ca174c98e18d0f6631/procrastinate/psycopg_connector.py#L206C15-L206C38) and [execute_query_all_async](https://github.com/procrastinate-org/procrastinate/blob/234f5f0ef3571cd9ff9053ca174c98e18d0f6631/procrastinate/psycopg_connector.py#L219C15-L219C38) functions.

**Comment by ewjoachim** [comment]
I wonder if it's the role of procrastinate to continuously retry, versus the process supervisor (systemd, kubernetes, ...) that's being used to handle the process. I would say it's a pretty critical failure if we can't access the DB, and in case it's wrong credentials or anything, we probably don't want the worker to keep trying ad nauseam.

Note: the `30 sec` value is a [psycopg_pool](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool)-controlled value, which you can override:
```python
PsycopgConnector(
    conninfo=get_postgres_connection_string(),
    kwargs={"prepare_threshold": None},
    timeout=3600*24*30  # Waiting up to a month
)
```

**Comment by gameveloster** [comment]
Letting a process supervisor monitor and restart the worker process on such critical failures is a good idea. 

But when I looked into it, I cant figure out how the processor supervisor can know that it has to restart the procrastinate worker process if the process didnt crash/terminate when it is suddenly unable to establish the DB connection.

**Comment by TkTech** [comment]
Ending up in a zombie state where it can't do any work and refuses to die is definitely a bug

**Comment by ewjoachim** [comment]
Wait, I'm lost, what is the current behaviour ? I thought that it crashed and exited with code 1 if it couldn't connect to the DB, and this is what I understand from your first message.

But then from the 2 previous messages, it seems you imply that it doesn't crash ?

**Comment by gameveloster** [comment]
Sorry I got confused. I tried reproducing the error a few more times and the process always exit/terminate when it encounters this exception.

So your idea of using a process supervisor will work and this is what I will go with, thank you!
