### ISSUE TITLE
App.import_paths not working

### ISSUE THREAD

**Issue by mecampbellsoup** [procrastinate-org/procrastinate#438]
I would like to invoke a worker process(es) using the CLI invocation, a la:

```shell
procrastinate --app=app.procrastinate.app worker
```

However, we also would like to "hook in" to the app initialization in order to do some setup work (e.g. DB connection pool, etc.).

That setup work is illustrated in this example `procrastinate.py` module:

```python
import asyncio

from procrastinate import AiopgConnector, App

from app.settings import database, DATABASE_URL

app = App(
    connector=AiopgConnector(dsn=DATABASE_URL),
    import_paths=['app.reconciler'],
)


async def main():
    await app.open_async()
    await database.connect()
    await app.run_worker_async(
        delete_jobs='successful',
    )


if __name__ == "__main__":
    print('SCRIPT MODE')
    print('__name__ == "__main__"')
    asyncio.run(main())
```
This allows me to run the `main()` function which does my setup work before initializing the worker. However this requires me to execute this process as a Python script - `python -m app.procrastinate` - which is fine, **except** my `reconcile` task no longer seems to be imported/loadable by my worker:

```
(⎈ minikube:cloud)➜  dev git:(mc/cloud-worker) ✗ k logs -n cloud deployments/cloud-app -c cloud-app-worker -f
SCRIPT MODE
__name__ == "__main__"
Task was not found: Task at reconcile cannot be imported: reconcile is not a valid path
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 14, in load_task
    task = utils.load_from_path(path, Task)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 27, in load_from_path
    raise exceptions.LoadFromPathError(f"{path} is not a valid path")
procrastinate.exceptions.LoadFromPathError: reconcile is not a valid path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 175, in process_job
    await self.run_job(job=job, worker_id=worker_id)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 240, in run_job
    task = self.load_task(task_name=task_name, worker_id=worker_id)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 222, in load_task
    task = tasks.load_task(task_name)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 16, in load_task
    raise exceptions.TaskNotFound(f"Task at {path} cannot be imported: {str(exc)}")
procrastinate.exceptions.TaskNotFound: Task at reconcile cannot be imported: reconcile is not a valid path

```
When I run the process via CLI, then `App.import_paths` are honored.
When I run the process as a Python script, `App.import_paths` does not seem to be honored.

Any suggestions? Thank you! 😄

**Comment by elemoine** [comment]
@mecampbellsoup could you please try something out for me? What if you create your Procrastinate App instance in a separate module? So, for example, you'd have an `app.py` module that just creates the app:

```py
from procrastinate import AiopgConnector, App

from app.settings import DATABASE_URL

app = App(
    connector=AiopgConnector(dsn=DATABASE_URL),
    import_paths=['app.reconciler'],
)
```

and a `main.py` module that takes care of starting the worker:

```py
import asyncio

from procrastinate import AiopgConnector, App

from yourapp.app import app
from yourapp.settings import database

async def main():
    await app.open_async()
    await database.connect()
    await app.run_worker_async(
        delete_jobs='successful',
    )

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by mecampbellsoup** [comment]
@elemoine sure, but how would I invoke the background worker process?

**Comment by elemoine** [comment]
@mecampbellsoup `python -m yourapp.main` as you wanted to do it.

**Comment by mecampbellsoup** [comment]
OK, this _almost_ works...!

```
(⎈ minikube:cloud)➜  dev git:(mc/cloud-worker) ✗ k logs deployments/cloud-app-worker -f
Found 2 pods, using pod/cloud-app-worker-7c8c76f5c8-76bm2
SCRIPT MODE
__name__ == "__main__"
Task was not found: Task at send_email cannot be imported: send_email is not a valid path
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 14, in load_task
    task = utils.load_from_path(path, Task)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 27, in load_from_path
    raise exceptions.LoadFromPathError(f"{path} is not a valid path")
procrastinate.exceptions.LoadFromPathError: send_email is not a valid path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 175, in process_job
    await self.run_job(job=job, worker_id=worker_id)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 240, in run_job
    task = self.load_task(task_name=task_name, worker_id=worker_id)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 222, in load_task
    task = tasks.load_task(task_name)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 16, in load_task
    raise exceptions.TaskNotFound(f"Task at {path} cannot be imported: {str(exc)}")
procrastinate.exceptions.TaskNotFound: Task at send_email cannot be imported: send_email is not a valid path
```

As a bit more context, we are running a FastAPI ASGI application with an ASGI-wrapped Django application which we use for internal endpoints (specifically we're using [`django-allauth`](https://django-allauth.readthedocs.io/en/latest/index.html) for user authentication).

As such I have a "sync" procrastinate app alongside an "async" app, a la:

```python
from procrastinate import AiopgConnector, App, Psycopg2Connector
from procrastinate.testing import InMemoryConnector

from app.settings import DATABASE_URL, env, TEST_ENV

app_connector = InMemoryConnector() if env == TEST_ENV else AiopgConnector(dsn=DATABASE_URL)
sync_app_connector = Psycopg2Connector(dsn=DATABASE_URL)

app = App(
    connector=app_connector,
    import_paths=['app.reconciler', 'app.tasks'],
)

sync_app = App(
    connector=sync_app_connector,
)
```

The `send_email` task it is now complaining about is decorated as a task by the `sync_app` so perhaps this error makes sense...

```python
import httpx
import sentry_sdk
from procrastinate import RetryStrategy

import app.settings as settings
from app.procrastinate import sync_app


# https://procrastinate.readthedocs.io/en/stable/howto/retry.html
# https://procrastinate.readthedocs.io/en/stable/reference.html#module-procrastinate.retry
@sync_app.task(name="send_email", retry=RetryStrategy(
    wait=5,
    exponential_wait=2
))
async def send_hubspot_email(data) -> None:
    if (settings.env == settings.PROD_ENV or settings.FORCE_SEND_EMAIL) and not settings.DISABLE_SEND_EMAIL:
        params = {"hapikey": settings.HUBSPOT_API_KEY}
        async with httpx.AsyncClient(base_url=settings.HUBSPOT_API_URL) as client:
            r = await client.post('marketing/v3/transactional/single-email/send', json=data, params=params)
            if r.status_code != 200:
                sentry_sdk.capture_message('Failed to send email')
    else:
        print('--------------------')
        print('Sending email:')
        print(data)
        print('--------------------')
```

**Comment by elemoine** [comment]
This sounds like a different issue. I guess the procrastinate worker, which uses the "async app", doesn't know about the "send_email" task which is registered in the "sync app".

**Comment by ewjoachim** [comment]
Just to understand better, can you detail what you use the `sync_app` for ?

**Comment by mecampbellsoup** [comment]
@ewjoachim yea, basically we having a "main" FastAPI ASGI app (asyncio Python) but we use a Django library called `django-allauth` under the hood for our app's login/logout/general auth functionality.

When I try to use a single procrastinate app with `AiopgConnector`, the Django "send email" tasks error when trying to enqueue them:

```
[cloud-app] Internal Server Error: /accounts/password/reset/
[cloud-app] Traceback (most recent call last):
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
[cloud-app]     response = get_response(request)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
[cloud-app]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
[cloud-app]     return callback(request, *args, **kwargs)
[cloud-app]   File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
[cloud-app]     return func(*args, **kwds)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
[cloud-app]     return self.dispatch(request, *args, **kwargs)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
[cloud-app]     return handler(request, *args, **kwargs)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/allauth/account/views.py", line 102, in post
[cloud-app]     response = self.form_valid(form)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/allauth/account/views.py", line 690, in form_valid
[cloud-app]     form.save(self.request)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/allauth/account/forms.py", line 561, in save
[cloud-app]     get_adapter(request).send_mail(
[cloud-app]   File "/cloud-app/./iam/adapters.py", line 9, in send_mail
[cloud-app]     send_mail(template_prefix, email, context)
[cloud-app]   File "/cloud-app/./iam/adapters.py", line 58, in send_mail
[cloud-app]     fn(email, context)
[cloud-app]   File "/cloud-app/./iam/adapters.py", line 25, in send_password_recovery_email
[cloud-app]     send_hubspot_email.defer(data=data)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 127, in defer
[cloud-app]     return self.configure().defer(**task_kwargs)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/procrastinate/jobs.py", line 163, in defer
[cloud-app]     job = self.job_manager.defer_job(job=job)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/procrastinate/manager.py", line 51, in defer_job
[cloud-app]     result = self.connector.execute_query_one(
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 118, in wrapper
[cloud-app]     return sync_await(awaitable=awaitable)
[cloud-app]   File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 164, in sync_await
[cloud-app]     loop = asyncio.get_event_loop()
[cloud-app]   File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
[cloud-app]     raise RuntimeError('There is no current event loop in thread %r.'
[cloud-app] RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.
[cloud-app] Exception: Expecting value: line 1 column 1 (char 0)
```
Previously I thought I had this licked - I just made a separate `sync_app` that uses the `Psycopg2Connector` instead - and rely on that to enqueue the "sync" Django tasks:

```python
import asyncio

from procrastinate import AiopgConnector, App, Psycopg2Connector
from procrastinate.testing import InMemoryConnector

from app.settings import database, DATABASE_URL, env, TEST_ENV

app_connector = InMemoryConnector() if env == TEST_ENV else AiopgConnector(dsn=DATABASE_URL)
sync_app_connector = Psycopg2Connector(dsn=DATABASE_URL)

app = App(
    connector=app_connector,
    import_paths=['app.reconciler', 'app.tasks'],
)

sync_app = App(
    connector=sync_app_connector,
)
```

However, this appears to no longer work (I have been moving a lot of things around lately as I try to figure out the right way to marry these two apps, our ASGI FastApi endpoints with our internal Django auth API) - here's the backtrace if you're curious:

```
[cloud-app-worker] ERROR:procrastinate.worker.worker:Task was not found: Task at send_email cannot be imported: send_email is not a valid path
[cloud-app-worker] Traceback (most recent call last):
[cloud-app-worker]   File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 14, in load_task
[cloud-app-worker]     task = utils.load_from_path(path, Task)
[cloud-app-worker]   File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 27, in load_from_path
[cloud-app-worker]     raise exceptions.LoadFromPathError(f"{path} is not a valid path")
[cloud-app-worker] procrastinate.exceptions.LoadFromPathError: send_email is not a valid path
[cloud-app-worker]
[cloud-app-worker] During handling of the above exception, another exception occurred:
[cloud-app-worker]
[cloud-app-worker] Traceback (most recent call last):
[cloud-app-worker]   File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 175, in process_job
[cloud-app-worker]     await self.run_job(job=job, worker_id=worker_id)
[cloud-app-worker]   File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 240, in run_job
[cloud-app-worker]     task = self.load_task(task_name=task_name, worker_id=worker_id)
[cloud-app-worker]   File "/usr/local/lib/python3.9/site-packages/procrastinate/worker.py", line 222, in load_task
[cloud-app-worker]     task = tasks.load_task(task_name)
[cloud-app-worker]   File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 16, in load_task
[cloud-app-worker]     raise exceptions.TaskNotFound(f"Task at {path} cannot be imported: {str(exc)}")
[cloud-app-worker] procrastinate.exceptions.TaskNotFound: Task at send_email cannot be imported: send_email is not a valid path
```

I'll update the issue if I can get this approach back in a working state soon!

P.S. I'm invoking the procrastinate worker as follows:

```yaml
... cloud-worker k8s deployment.yaml
command: ["procrastinate"]
args:
  - "--verbose"
  - "--app=app.procrastinate.app"
  - "worker"
  - "--delete-jobs=successful"
...
```

**Comment by mecampbellsoup** [comment]
Here is a condensed view of how we import the Django app and mount it as an ASGI sub-app.

```python
# app/django.py
"""ASGI Django app"""

from fastapi.middleware.wsgi import WSGIMiddleware

from gatekeeper.wsgi import application

django_app = WSGIMiddleware(application)
```

```python
# app/main.py
from app.django import django_app

...

if settings.ALLOW_ALLAUTH_HTML:
    app.mount('/', django_app)
else:
    for social in ('github', 'google'):
        paths = (
            f'/accounts/{social}/login/',
            f'/accounts/{social}/login/callback/'
        )
        for path in paths:
            app.add_route(path, django_app, methods=['GET'])
```
We leverage the ASGI protocol to mount the whole app, or specific routes (depending on some settings), relying on the `WSGIMiddleware` to wrap a WSGI app so it can speak ASGI.

https://fastapi.tiangolo.com/advanced/wsgi/#using-wsgimiddleware

**Comment by elemoine** [comment]
@mecampbellsoup I am interested to see how you declare your "send_email" task.

**Comment by mecampbellsoup** [comment]
My `send_hubspot_email` (formerly `name='send_email'`) task is working again - I just removed the `name` argument I was passing to `@sync_app.task()`:

```python
# https://procrastinate.readthedocs.io/en/stable/howto/retry.html
# https://procrastinate.readthedocs.io/en/stable/reference.html#module-procrastinate.retry
@sync_app.task(retry=RetryStrategy(
    wait=5,
    exponential_wait=2
))
```

**Comment by ewjoachim** [comment]
Very interesting, thanks a lot for sharing !

I'm wondering is a way to go could be to add `App().with_connector(connector=...)` which would send you a copy of the app but with a different connector. Without this, you may approximate this by manually setting a few things on your sync_app to match the corresponding attributes on the app. I think I'll try to reproduce with a minimal example at some point (or feel free to provide one if you want). I don't know when I'll be able to tackle this.

**Comment by mecampbellsoup** [comment]
Sounds good @ewjoachim if anything becomes more urgent I'll reach out again - thanks! I'll look into `with_connector` as well, sounds promising...

**Comment by ewjoachim** [comment]
(just to be clear, `with_connector` doesn't exist yet, I'm suggesting we implement it)

**Comment by mecampbellsoup** [comment]
> (just to be clear, `with_connector` doesn't exist yet, I'm suggesting we implement it)

Ah! I was wondering why I couldn't find it! 🤣 

Yes, such a method could basically just yield the app instance with the new/changed connector, and automatically switch it back when leaving the context (I'm picturing usage with a context manager primarily).

**Comment by ewjoachim** [comment]
Hm, I think a context manager would have strange side effects because when it ends, the instance would be modified... Maybe the "with" in the suggested method name is confusing.

**Comment by ewjoachim** [comment]
I'm wondering: have you tried using the aiopg connector everywhere (including in sync contexts) ? Was there something that made you come back from it ?

**Comment by mecampbellsoup** [comment]
> I'm wondering: have you tried using the app with the aiopg connector everywhere (including in sync contexts) ? Was there something that made you come back from it ?

We have a hybrid Django + ASGI application (we use a Django auth library, [`django-allauth`](https://django-allauth.readthedocs.io/en/latest/index.html), for all our authentication API endpoints). We cannot use the async aiopg connector in Django context, right?

https://procrastinate.readthedocs.io/en/stable/howto/django.html

**Comment by ewjoachim** [comment]
I could be wrong but I believe it would work (as long as you're ok that procrastinate will have its own DB connection and not share with the rest of the pool).
Where I might be wrong is in the sense that event loops and Django's threading habits might not work well together, but I'm not 100% sure it's problematic.

Shall we try ? :D

**Comment by mecampbellsoup** [comment]
Sure; when I try using our async application (uses `AiopgConnector`) the following error occurs:

```
Internal Server Error: /accounts/password/reset/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/usr/local/lib/python3.9/site-packages/allauth/account/views.py", line 690, in form_valid
    form.save(self.request)
  File "/usr/local/lib/python3.9/site-packages/allauth/account/forms.py", line 561, in save
    get_adapter(request).send_mail(
  File "/cloud-app/./iam/adapters.py", line 9, in send_mail
    send_mail(template_prefix, email, context)
  File "/cloud-app/./iam/adapters.py", line 58, in send_mail
    fn(email, context)
  File "/cloud-app/./iam/adapters.py", line 25, in send_password_recovery_email
    send_hubspot_email.defer(data=data)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/tasks.py", line 127, in defer
    return self.configure().defer(**task_kwargs)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/jobs.py", line 163, in defer
    job = self.job_manager.defer_job(job=job)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/manager.py", line 51, in defer_job
    result = self.connector.execute_query_one(
  File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 118, in wrapper
    return sync_await(awaitable=awaitable)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 164, in sync_await
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.
Exception: Expecting value: line 1 column 1 (char 0)
```

**Comment by ewjoachim** [comment]
Ah yes, event loop problems.

**Comment by ewjoachim** [comment]
If you have the opportunity to test the PR on #463 and confirm it solves the issue for you, that would be great :)
