### ISSUE TITLE
Blueprints get duplicate namespace prefixes in tests

### ISSUE THREAD

**Issue by kbakk** [procrastinate-org/procrastinate#521]
I am initializing the app several times in my tests, and after upgrading to 0.23.0 I noticed that the tests have started to fail, with `procrastinate.exceptions.TaskNotFound`:

```
ERROR [procrastinate.worker] Task was not found: 
    Task cannot be imported.
    
Traceback (most recent call last):
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/file-processing-trigger--C-Yay8K-py3.9/lib/python3.9/site-packages/procrastinate/worker.py", line 206, in find_task
    return self.app.tasks[task_name]
KeyError: 'mediabank_ingest:trigger_ingest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/file-processing-trigger--C-Yay8K-py3.9/lib/python3.9/site-packages/procrastinate/worker.py", line 169, in process_job
    await self.run_job(job=job, worker_id=worker_id)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/file-processing-trigger--C-Yay8K-py3.9/lib/python3.9/site-packages/procrastinate/worker.py", line 213, in run_job
    task = self.find_task(task_name=task_name)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/file-processing-trigger--C-Yay8K-py3.9/lib/python3.9/site-packages/procrastinate/worker.py", line 208, in find_task
    raise exceptions.TaskNotFound
procrastinate.exceptions.TaskNotFound: 
    Task cannot be imported.
```

I noticed when debugging the tests that my tasks had duplicated their prefixes:

![image](https://user-images.githubusercontent.com/24817039/148362262-0ecf87ef-ab21-4d11-8841-3d7a17e05139.png)

I have a function scoped fixture that returns the app, which is created this way

```py
def get_worker_app(connector):
    app = procrastinate.App(connector=connector)
    app.open()
    app.add_tasks_from(debug_to_disk.bp, namespace=module_to_namespace(debug_to_disk.__name__))
    app.add_tasks_from(mediabank_ingest.bp, namespace=module_to_namespace(mediabank_ingest.__name__))
    return app

@pytest.fixture
def app():
    app = get_worker_app(connector=InMemoryConnector())
    yield app
    # Reset the "in-memory pseudo-database" between tests:
    app.connector.reset()
```

So this gets called multiple times. It seems like the blueprint persists the name of the task, including the prefix. 

Here's the blueprint:

```py
bp = Blueprint()

@bp.task(name="write_to_file")
def write_to_file(path: str, content: str):
    pathlib.Path(path).write_text(content)
    logger.info(f"Wrote content to: {path}")
```

I've been able to work around this by having a reset_blueprint fixture, that I'm using now:

```py
@pytest.fixture
def reset_blueprints():
    # rerun imports, to get a reset blueprints, else they will persist data from previous runs
    importlib.reload(file_processing_trigger.tasks.debug_to_disk)
    importlib.reload(file_processing_trigger.tasks.mediabank_ingest)

@pytest.fixture
def app(reset_blueprints):
    ...
```

I'm not sure if this is a bug, or something else but `importlib.reload` seems like a workaround. 

Sorry about no proper reproducer, let me if that's needed and I can try to set that up.

**Comment by ewjoachim** [comment]
Hello !

Thanks for the bug report ! I'm not that surprised to see thins kind of behaviours as the namespacing feature had not been written with the tests in mind. I'll see if I can get a fix out there.

**Comment by ewjoachim** [comment]
Here's how it's done in the procrastinate codebase, and it's suboptimal :/
https://github.com/procrastinate-org/procrastinate/blob/a30a514cc68a7535e67729baba5d692ef21f4a5b/tests/conftest.py#L170-L175

**Comment by ewjoachim** [comment]
Ok, so the problem is that when we register a task, its name is updated with the new name.
This side-effect is problematic, but it's necessary to do `task.defer()`

One simple (but wrong) solution could be to adapt the `utils.add_namespace` function to not do anything if the namespace is already present on the function. But I believe it would be the wrong solution.

I believe there might be a solution where we keep a (weak) ref to blueprints & apps in the tasks, and compute the name dynamically depending on what `self.blueprint` points to.

I've made a failing test, now it's time to brainstorm :)

**Comment by ewjoachim** [comment]
Yep, the problem is conceptual. Or there is a smart solution we haven't found yet.
