### ISSUE TITLE
psycopg2 error when trying to execute task in README

### ISSUE THREAD

**Issue by bmarsh9** [procrastinate-org/procrastinate#742]
Hi there - I'm looking for alternatives to RQ and stumbled on this project. However when I'm trying to execute the example at the top of the README (e.g. `mycode.py`), I receive a error. Im almost sure its on my end... but cant figure out why. Im getting the following errors:

```
App is instantiated in the main Python module (mycode.py). See https://procrastinate.readthedocs.io/en/stable/discussions.html#top-level-app .
NoneType: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/aiopg_connector.py", line 31, in wrapped
    return await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/aiopg_connector.py", line 67, in wrapped
    return await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/aiopg_connector.py", line 269, in execute_query_one_async
    await cursor.execute(query, self._wrap_json(arguments))
  File "/usr/local/lib/python3.8/dist-packages/aiopg/connection.py", line 426, in execute
    await self._conn._poll(waiter, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiopg/connection.py", line 881, in _poll
    await asyncio.wait_for(self._waiter, timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/dist-packages/aiopg/connection.py", line 788, in _ready
    state = self._conn.poll()
psycopg2.errors.UndefinedFunction: function procrastinate_defer_job(unknown, unknown, unknown, unknown, unknown, unknown) does not exist
LINE 1: SELECT procrastinate_defer_job('sums', 'mycode.sum', NULL, N...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mycode.py", line 15, in <module>
    sum.defer(a=3, b=5)
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/tasks.py", line 129, in defer
    return self.configure().defer(**task_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/jobs.py", line 162, in defer
    job = self.job_manager.defer_job(job=job)
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/manager.py", line 52, in defer_job
    result = self.connector.execute_query_one(
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/utils.py", line 149, in wrapper
    return sync_await(awaitable=awaitable)
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/utils.py", line 200, in sync_await
    return loop.run_until_complete(awaitable)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/procrastinate/aiopg_connector.py", line 35, in wrapped
    raise exceptions.ConnectorException from exc
procrastinate.exceptions.ConnectorException:
    Database error.
```

`mycode.py`

```
# mycode.py
import procrastinate

# Make an app in your code
app = procrastinate.App(connector=procrastinate.AiopgConnector(user="db1",password="db1",host="localhost",database="db1"))

# Then define tasks
@app.task(queue="sums")
def sum(a, b):
    with open("myfile", "w") as f:
        f.write(str(a + b))

with app.open():
    # Launch a job
    sum.defer(a=3, b=5)

    # Somewhere in your program, run a worker (actually, it's often a
    # different program than the one deferring jobs for execution)
    app.run_worker(queues=["sums"])
```

Next, I'm running the following and then the error appears
```
export PROCRASTINATE_APP="mycode.app"

# Launch a job (This is when the error is shown)
procrastinate defer mycode.sum '{"a": 3, "b": 5}'
```

**Comment by ewjoachim** [comment]
Wow you're absolutely right, the doc for applying migrations the the schema is not very visible compared to the rest of the code in the readme and such.

If you're following the quickstart doc, the relevant part is here: https://procrastinate.readthedocs.io/en/stable/quickstart.html#prepare-the-database
The detailed instructions are in https://procrastinate.readthedocs.io/en/stable/howto/migrations.html#migrate-the-procrastinate-schema

Also, you might be unaware that we had a doc, given several links were 404, sorry about that, it's now fixed.

If you want to get a feeling of how the lib work, I highly suggest the Quickstart doc linked above.

**Comment by ewjoachim** [comment]
In https://github.com/procrastinate-org/procrastinate/pull/744, I've added a link to the quickstart at the top of the readme. The quickstart is the doc dedicated to making sure your first experience manipulating Procrastinate goes succesfully.

**Comment by bmarsh9** [comment]
Awesome - Ill give that a try. Thanks for the quick reply! @ewjoachim
