### ISSUE TITLE
How to periodically schedule tasks without decorators

### ISSUE THREAD

**Issue by bmarsh9** [procrastinate-org/procrastinate#747]
Apologies for all the questions... but Im trying to periodically schedule tasks without decorators. I don't get any errors... but the task is never scheduled and executed. Code examples below and [relevant docs Im following](https://procrastinate.readthedocs.io/en/stable/howto/cron.html#scheduling-a-job-multiple-times-with-multiple-arguments)

```
## tasks.py

@bg_app.task(name="add-sum", queue="sums")
def sum(a, b, **kwargs):
    print("testing!")
    return a + b
```

Without a `cron` decorator on the function above, I want to periodically schedule the task. Here is what I've tried. I don't get any errors, but the task is never placed in the `procrastinate_periodic_defers` table.
```
>>> bg_app.periodic(name="add-sum",queue="test",cron="* * * * *",task_kwargs={"a": 5,"b":7},periodic_id=3)(task=tasks.sum)
```
```
# internal method
>>> bg_app.periodic_deferrer.register_task(task=task,cron="* * * * *",periodic_id=10,configure_kwargs={"a":5,"b":7})
INFO:procrastinate.periodic:Registering task add-sum with periodic id 10 to run periodically with cron * * * * *
PeriodicTask(task=<procrastinate.tasks.Task object at 0x7f1713d89fd0>, cron='* * * * *', periodic_id=10, configure_kwargs={'a': 5, 'b': 7})
```

Database tables that I would think would populate
```
db1=# select * from procrastinate_periodic_defers;
 id | task_name | defer_timestamp | job_id | queue_name | periodic_id
----+-----------+-----------------+--------+------------+-------------
(0 rows)
```

```
db1=# select * from procrastinate_events order by id desc limit 4;
 id | job_id |   type   |              at
----+--------+----------+-------------------------------
 87 |     23 | failed   | 2023-02-22 18:38:11.649352+00
 86 |     23 | started  | 2023-02-22 18:38:11.643937+00
 84 |     22 | failed   | 2023-02-22 18:29:00.546381+00
 83 |     22 | started  | 2023-02-22 18:29:00.535542+00
(4 rows)
```

Lastly, the worker is started before all the commands above. But here is the debug log

```
DEBUG:procrastinate.utils:Importing module app.worker.tasks
DEBUG:procrastinate.app:All tasks imported
INFO:procrastinate.worker.worker:Starting worker on all queues
DEBUG:procrastinate.signals:Installing signal handler
DEBUG:procrastinate.utils:Started single_worker
DEBUG:procrastinate.utils:Started periodic_deferrer
DEBUG:procrastinate.utils:Started listener
INFO:procrastinate.periodic:No periodic task found, periodic deferrer will not run.
DEBUG:procrastinate.worker.worker:Waiting for new jobs on all queues
DEBUG:procrastinate.worker.worker:Waiting for new jobs on all queues
DEBUG:procrastinate.signals:Resetting previous signal handler
```

**Comment by ewjoachim** [comment]
> Apologies for all the questions

Apologies for the shortcomings in the project :)
(psst, by the way: https://github.com/procrastinate-org/procrastinate/discussions/748 )

From the `>>>` in your code above, I'm getting the feeling that this was executed as a one-off in a shell. This is not how it works. Procrastinate doesn't store the cron schedule in the DB. The `procrastinate_periodic_defers` table is here to keep track of when a periodic task was deferred in the past so that we don't launch periodic tasks twice for the same task on the same period.

Instead, if you don't use the decorated form, it's still expected that each workers (well, at least one and preferably more than one in case the one worker goes down, ideally all you workers) run the call to `app.periodic` for every task you want to run periodically.

If you plan to have the periodic schedule be dynamic, you may want to read https://github.com/procrastinate-org/procrastinate/issues/564

Does this make sense ?

**Comment by bmarsh9** [comment]
Would love to contribute more. Just to clarify - I'm calling `bg_app.periodic` within a Flask route, but I guess its functionally the same as a shell. 

But understood - I think Ill adopt your suggestion:

```
That say there is another possibility which I believe will be much easier.

1. When users schedule tasks, write this in an SQL table
2. Have a single normal periodic task that runs as frequently as the most frequent setting your users can schedule tasks to (e.g. 1/min if that's the most often they can do it). On each run, the periodic task you implement will read your SQL table, determine if something needs to be run for the received timestamp, defer corresponding tasks and that's it.

```

I think that will solve it!

**Comment by ewjoachim** [comment]
Great !

Given it's the second time this explaination helps someone, maybe we should move it to the documentation.

**Comment by bmarsh9** [comment]
When I get a chance to write it, I'm happy to provide the code examples in case anyone else has this issue

**Comment by bmarsh9** [comment]
Hate to re-open this... but running into #609 now. Tried to implement the async/await (and without it) but still throws the same error (shown at bottom). The `scheduler` function below is the one that gathers tasks from the SQL table, checks if its "ready" to execute and then defers it. 

```
@bg_app.periodic(cron="* * * * *")
@bg_app.task(name="scheduler", queue="scheduler")
async def scheduler(timestamp: int):
    # query tasks in the database
    # for each task, check if its ready to execute and then defer it
    await bg_app.configure_task(
        name="add-sum",
        lock="add-sum",
        schedule_in={"seconds":10},
        queue="12345").defer(a=5, b=7)
```

```
@bg_app.task(name="add-sum", queue="sums")
def sum(a, b, **kwargs):
    return a + b
```


```
ERROR:procrastinate.worker.worker:Job scheduler[55](timestamp=1677168300) ended with status: Error, lasted 0.053 s
Traceback (most recent call last):
  File "/home/bmarshall/projects/test/prod-gapps/venv/lib/python3.8/site-packages/procrastinate/worker.py", line 231, in run_job
    task_result = await task_result
  File "/home/bmarshall/projects/test/prod-gapps/app/worker/tasks.py", line 26, in scheduler
    sum.defer(a=5, b=7)
  File "/home/bmarshall/projects/test/prod-gapps/venv/lib/python3.8/site-packages/procrastinate/tasks.py", line 129, in defer
    return self.configure().defer(**task_kwargs)
  File "/home/bmarshall/projects/test/prod-gapps/venv/lib/python3.8/site-packages/procrastinate/jobs.py", line 162, in defer
    job = self.job_manager.defer_job(job=job)
  File "/home/bmarshall/projects/test/prod-gapps/venv/lib/python3.8/site-packages/procrastinate/manager.py", line 52, in defer_job
    result = self.connector.execute_query_one(
  File "/home/bmarshall/projects/test/prod-gapps/venv/lib/python3.8/site-packages/procrastinate/utils.py", line 149, in wrapper
    return sync_await(awaitable=awaitable)
  File "/home/bmarshall/projects/test/prod-gapps/venv/lib/python3.8/site-packages/procrastinate/utils.py", line 200, in sync_await
    return loop.run_until_complete(awaitable)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
```

**Comment by ewjoachim** [comment]
Yeah that's https://github.com/procrastinate-org/procrastinate/issues/751 and it's really getting annoying.
