### ISSUE TITLE
Missing psycopg 'binary' implementation extra since 0.30.0?

### ISSUE THREAD

**Issue by ashleyheath** [procrastinate-org/procrastinate#880]
```
Traceback (most recent call last):
<trimmed>
2023-12-27T14:52:56.489748780Z     import procrastinate
2023-12-27T14:52:56.489765680Z   File "/code/.venv/lib/python3.11/site-packages/procrastinate/__init__.py", line 8, in <module>
2023-12-27T14:52:56.489772822Z     from procrastinate.psycopg_connector import PsycopgConnector
2023-12-27T14:52:56.489825630Z   File "/code/.venv/lib/python3.11/site-packages/procrastinate/psycopg_connector.py", line 6, in <module>
2023-12-27T14:52:56.489846036Z     import psycopg
2023-12-27T14:52:56.489930920Z   File "/code/.venv/lib/python3.11/site-packages/psycopg/__init__.py", line 9, in <module>
2023-12-27T14:52:56.490090247Z     from . import pq  # noqa: F401 import early to stabilize side effects
2023-12-27T14:52:56.490108558Z     ^^^^^^^^^^^^^^^^
2023-12-27T14:52:56.490116210Z   File "/code/.venv/lib/python3.11/site-packages/psycopg/pq/__init__.py", line 114, in <module>
2023-12-27T14:52:56.490339001Z     import_from_libpq()
2023-12-27T14:52:56.490353415Z   File "/code/.venv/lib/python3.11/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
2023-12-27T14:52:56.490515846Z     raise ImportError(
2023-12-27T14:52:56.490529522Z ImportError: no pq wrapper available.
2023-12-27T14:52:56.490535698Z Attempts made:
2023-12-27T14:52:56.490541408Z - couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
2023-12-27T14:52:56.490547388Z - couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
2023-12-27T14:52:56.490553206Z - couldn't import psycopg 'python' implementation: libpq library not found
```

Looking at #863, `psycopg = {extras = ["pool"], version = "^3.1.13"}` was added but without the `"binary"` extra package. This causes an import error for existing users who don't currently declare the depdendency directly.

Easily worked around but probably a question for @aleksandr-shtaub as to whether the omission was deliberate (i.e. to allow users of procrastinate which of the 3 implementations they use) or should we add the dependency explicitly (which would be consistent as `"psycopg2-binary"` is alreay there).

**Comment by ewjoachim** [comment]
That might be my fault, I reworked the commits quite a bit.

I'll add it, sorry for the noise !

**Comment by ewjoachim** [comment]
Released: https://pypi.org/project/procrastinate/0.33.0/
