### ISSUE TITLE
AiopgConnector fails to connect

### ISSUE THREAD

**Issue by Vladimir-Filimonov** [procrastinate-org/procrastinate#908]
Hey all, 

I tried to use AiopgConnector but getting following error on opening the app:

> psycopg2.ProgrammingError: invalid dsn: invalid connection option "enable_json"

Full trace:
```
App is instantiated in the main Python module (test_aiopg.py). See https://procrastinate.readthedocs.io/en/stable/discussions.html#top-level-app
Traceback (most recent call last):
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/procrastinate/contrib/psycopg2/psycopg2_connector.py", line 26, in wrapped
    return func(*args, **kwargs)
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/procrastinate/contrib/psycopg2/psycopg2_connector.py", line 160, in _create_pool
    return psycopg2.pool.ThreadedConnectionPool(**pool_args)
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/psycopg2/pool.py", line 161, in __init__
    AbstractConnectionPool.__init__(
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/psycopg2/pool.py", line 59, in __init__
    self._connect()
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/psycopg2/pool.py", line 63, in _connect
    conn = psycopg2.connect(*self._args, **self._kwargs)
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 121, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/psycopg2/extensions.py", line 168, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "enable_json"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/UserX/git/proc_test/test_aiopg.py", line 18, in <module>
    with task_manager.open():
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/procrastinate/app.py", line 286, in open
    self.connector.get_sync_connector().open(pool_or_engine)
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/procrastinate/contrib/psycopg2/psycopg2_connector.py", line 155, in open
    self._pool = self._create_pool(self._pool_args)
  File "/Users/UserX/git/proc_test/.venv/lib/python3.9/site-packages/procrastinate/contrib/psycopg2/psycopg2_connector.py", line 30, in wrapped
    raise exceptions.ConnectorException from exc
procrastinate.exceptions.ConnectorException: 
    Database error.
```

Full code that I'm using and starting with `python test_aiopg.py`
```python
from procrastinate import BaseConnector, App
from procrastinate.contrib.aiopg import aiopg_connector

dsn = "postgres://user:pass@localhost:5432/dbname"

connector = aiopg_connector.AiopgConnector(
        dsn=dsn,
        maxsize=4,
        minsize=4
)

task_manager = App(connector=connector)

@task_manager.task(queue="sums")
def sum(a, b):
    print('{} + {} = {}'.format(a, b, a+b))

with task_manager.open():
    # Launch a job
    sum.defer(a=3, b=5)

task_manager.run_worker(queues=["sums"])
```

If I go to [psycopg2/extensions.py line 166](https://github.com/psycopg/psycopg2/blob/master/lib/extensions.py#L166) and add print of dsn there I'm seeing following printed:
`user=user password=pass dbname=dbname host=localhost port=5432 enable_json=False enable_hstore=False enable_uuid=False maxsize=4 minsize=4`

Looks like enable_json, enable_hstore and enable_uuid passed as kwards to psycopg2 to build DSN for synchronous connector which doesn't seem right. 
So if I go to [aiopg_connector.py line 154](https://github.com/procrastinate-org/procrastinate/blob/main/procrastinate/contrib/aiopg/aiopg_connector.py#L154) and add there few additional pops like:
```
args_copy.pop("enable_json", None)
args_copy.pop("enable_hstore", None)
args_copy.pop("enable_uuid", None)
args_copy.pop("maxsize", None)
args_copy.pop("minsize", None)
```
everything suddenly starts to work. But that doesn't feel right. Either I'm missing something (most likely) or there is a bug/test coverage issue.

**Comment by ewjoachim** [comment]
Hm, something must have broken in the recent changes around this module.
Here's the diff:

`git diff bec7eb -M -- procrastinate/aiopg_connector.py procrastinate/contrib/aiopg/aiopg_connector.py`



```diff
diff --git a/procrastinate/aiopg_connector.py b/procrastinate/contrib/aiopg/aiopg_connector.py
similarity index 87%
rename from procrastinate/aiopg_connector.py
rename to procrastinate/contrib/aiopg/aiopg_connector.py
index 95ecd2a..0290558 100644
--- a/procrastinate/aiopg_connector.py
+++ b/procrastinate/contrib/aiopg/aiopg_connector.py
@@ -1,15 +1,19 @@
+from __future__ import annotations
+
 import asyncio
 import functools
 import logging
-from typing import Any, Callable, Coroutine, Dict, Iterable, List, Optional
+from typing import Any, Callable, Coroutine, Iterable
 
 import aiopg
 import psycopg2
 import psycopg2.errors
+import psycopg2.extras
 import psycopg2.sql
 from psycopg2.extras import Json, RealDictCursor
 
-from procrastinate import connector, exceptions, sql
+from procrastinate import connector, exceptions, sql, utils
+from procrastinate.contrib.psycopg2 import psycopg2_connector
 
 logger = logging.getLogger(__name__)
 
@@ -81,8 +85,8 @@ class AiopgConnector(connector.BaseAsyncConnector):
     def __init__(
         self,
         *,
-        json_dumps: Optional[Callable] = None,
-        json_loads: Optional[Callable] = None,
+        json_dumps: Callable | None = None,
+        json_loads: Callable | None = None,
         **kwargs: Any,
     ):
         """
@@ -135,17 +139,31 @@ class AiopgConnector(connector.BaseAsyncConnector):
             Passed to aiopg. Initial connections are not opened when the connector
             is created, but at first use of the pool.
         """
-        self._pool: Optional[aiopg.Pool] = None
+        self._pool: aiopg.Pool | None = None
         self._pool_externally_set: bool = False
         self.json_dumps = json_dumps
         self.json_loads = json_loads
         self._pool_args = self._adapt_pool_args(kwargs, json_loads)
-        self._lock: Optional[asyncio.Lock] = None
+        self._lock: asyncio.Lock | None = None
+        self._sync_connector: connector.BaseConnector | None = None
+
+    def get_sync_connector(self) -> connector.BaseConnector:
+        if self._pool:
+            return self
+        args_copy = dict(self._pool_args)
+        args_copy.pop("on_connect", None)
+        if self._sync_connector is None:
+            self._sync_connector = psycopg2_connector.Psycopg2Connector(
+                json_dumps=self.json_dumps,
+                json_loads=self.json_loads,
+                **args_copy,
+            )
+        return self._sync_connector
 
     @staticmethod
     def _adapt_pool_args(
-        pool_args: Dict[str, Any], json_loads: Optional[Callable]
-    ) -> Dict[str, Any]:
+        pool_args: dict[str, Any], json_loads: Callable | None
+    ) -> dict[str, Any]:
         """
         Adapt the pool args for ``aiopg``, using sensible defaults for Procrastinate.
         """
@@ -176,7 +194,7 @@ class AiopgConnector(connector.BaseAsyncConnector):
             raise exceptions.AppNotOpen
         return self._pool
 
-    async def open_async(self, pool: Optional[aiopg.Pool] = None) -> None:
+    async def open_async(self, pool: aiopg.Pool | None = None) -> None:
         if self._pool:
             return
         if pool:
@@ -185,9 +203,12 @@ class AiopgConnector(connector.BaseAsyncConnector):
         else:
             self._pool = await self._create_pool(self._pool_args)
 
-    @staticmethod
     @wrap_exceptions
-    async def _create_pool(pool_args: Dict[str, Any]) -> aiopg.Pool:
+    async def _create_pool(self, pool_args: dict[str, Any]) -> aiopg.Pool:
+        if self._sync_connector is not None:
+            await utils.sync_to_async(self._sync_connector.close)
+            self._sync_connector = None
+
         return await aiopg.create_pool(**pool_args)
 
     @wrap_exceptions
@@ -213,7 +234,7 @@ class AiopgConnector(connector.BaseAsyncConnector):
             while self._pool._free:
                 self._pool._free.popleft().close()
 
-    def _wrap_json(self, arguments: Dict[str, Any]):
+    def _wrap_json(self, arguments: dict[str, Any]):
         return {
             key: Json(value, dumps=self.json_dumps)
             if isinstance(value, dict)
@@ -227,22 +248,9 @@ class AiopgConnector(connector.BaseAsyncConnector):
     # Because of this, it's easier to have 2 distinct methods for executing from
     # a pool or from a connection
 
-    def _prepare_for_interpolation(self, query, has_arguments):
-        # psycopg2 thinks ``%`` are for it to process. If we have ``%`` in our query,
-        # like in RAISE, we need it to be passed to the database as-is, which means
-        # we need to escape the % by doubling it.
-        return (
-            query
-            if has_arguments or not isinstance(query, str)
-            else query.replace("%", "%%")
-        )
-
     @wrap_exceptions
     @wrap_query_exceptions
     async def execute_query_async(self, query: str, **arguments: Any) -> None:
-        query = self._prepare_for_interpolation(
-            query=query, has_arguments=bool(arguments)
-        )
         with await self.pool.cursor() as cursor:
             await cursor.execute(query, self._wrap_json(arguments))
 
@@ -251,9 +259,6 @@ class AiopgConnector(connector.BaseAsyncConnector):
     async def _execute_query_connection(
         self, query: str, connection: aiopg.Connection, **arguments: Any
     ) -> None:
-        query = self._prepare_for_interpolation(
-            query=query, has_arguments=bool(arguments)
-        )
         async with connection.cursor() as cursor:
             await cursor.execute(query, self._wrap_json(arguments))
 
@@ -261,10 +266,7 @@ class AiopgConnector(connector.BaseAsyncConnector):
     @wrap_query_exceptions
     async def execute_query_one_async(
         self, query: str, **arguments: Any
-    ) -> Dict[str, Any]:
-        query = self._prepare_for_interpolation(
-            query=query, has_arguments=bool(arguments)
-        )
+    ) -> dict[str, Any]:
         with await self.pool.cursor() as cursor:
             await cursor.execute(query, self._wrap_json(arguments))
 
@@ -274,16 +276,13 @@ class AiopgConnector(connector.BaseAsyncConnector):
     @wrap_query_exceptions
     async def execute_query_all_async(
         self, query: str, **arguments: Any
-    ) -> List[Dict[str, Any]]:
-        query = self._prepare_for_interpolation(
-            query=query, has_arguments=bool(arguments)
-        )
+    ) -> list[dict[str, Any]]:
         with await self.pool.cursor() as cursor:
             await cursor.execute(query, self._wrap_json(arguments))
 
             return await cursor.fetchall()
 
-    def _make_dynamic_query(self, query: str, **identifiers: str) -> str:
+    def _make_dynamic_query(self, query: str, **identifiers: str) -> Any:
         return psycopg2.sql.SQL(query).format(
             **{
                 key: psycopg2.sql.Identifier(value)
```

**Comment by ewjoachim** [comment]
Ah, the issue is due to the aiopg connector detecting that it's a sync usage and invoking a psycopg2 connector instead. I'll keep investigating.

**Comment by ewjoachim** [comment]
Ok, I've added a reproducing test, then resolved it. Will merge & release shortly
